---
- name: "Check"
  hosts: sdp-mwportal
  remote_user: mwatch

  tasks:
        - name: "Check java home"
          become: yes
          become_user: mwatch
          command: "echo $JAVA_HOME"
          register: "java_home"

        - name: "Debug java_home.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ java_home.stdout_lines }}

        - name: "check hosts"
          become: yes
          become_user: mwatch
          command: "cat /etc/hosts"
          register: "etc_hosts"

        - name: "Debug etc_hosts.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ etc_hosts.stdout_lines }}
          
        - name: "Verify httpd process"
          sudo: yes
          shell: "ps -ef |grep httpd | grep -v grep | awk '{ print $1  echo " " $2 echo " " $3  echo " " $6}'"
          register: "httpd_process"
        
        - name: "Debug httpd_process.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ httpd_process.stdout_lines }}
          
        - name: "Verify tomcat process"
          sudo: yes
          shell: "ps -ef |grep tomcat | grep -v grep | awk '{ print $1  echo " " $2 echo " " $3  echo " " $9}'"
          register: "tomcat_process"
           
        - name: "Debug tomcat_process.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ tomcat_process.stdout_lines }}
          
        - name: "Verify redis process"
          sudo: yes
          shell: "ps -ef |grep redis | grep -v grep | awk '{ print $1  echo " " $2 echo " " $3  echo " " $9}'"
          register: "redis_process"
          
        - name: "Debug redis_process.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ redis_process.stdout_lines }}        

        - name: "Verify ldap process"
          sudo: yes
          shell: "ps -ef |grep ldap | grep -v grep | awk '{ print $1  echo " " $2 echo " " $3  echo " " $9}'"
          register: "ldap_process"
         
        - name: "Debug ldap_process.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ ldap_process.stdout_lines }}          