---
- name: "Check"
  hosts: sdp-mwportal
  remote_user: mwatch

  tasks:
        - name: "Check java home"
          become: yes
          become_user: mwatch
          command: "echo $JAVA_HOME"
          register: "java_home"

        - name: "Debug java_home.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ java_home.stdout_lines }}

        - name: "check hosts"
          become: yes
          become_user: mwatch
          command: "cat /etc/hosts"
          register: "etc_hosts"

        - name: "Debug etc_hosts.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ etc_hosts.stdout_lines }}
        - name: "Verify httpd process"
          sudo: yes
          command: "ps -ef |grep httpd"
          register: "httpd_process"

        #- name: "Debug portal_script"
         # become: yes
         # become_user: mwatch
          #debug: "var=portal_script"
        - name: "Verify tomcat process"
          sudo: yes
          shell: "ps -ef |grep tomcat"
          

        #- name: "Debug portal_script"
         # become: yes
         # become_user: mwatch
          #debug: "var=portal_script"
        - name: "Verify redis process"
          sudo: yes
          shell: "ps -ef |grep redis"
        

        #- name: "Debug portal_script"
         # become: yes
         # become_user: mwatch
          #debug: "var=portal_script"
        - name: "Verify ldap process"
          sudo: yes
          shell: "ps -ef |grep ldap"
         

        #- name: "Debug portal_script"
         # become: yes
         # become_user: mwatch
          #debug: "var=portal_script"          