---
- name: "Check"
  hosts: sdp-mwportal
  remote_user: mwatch

  tasks:
        - name: "Check java home"
          become: yes
          become_user: mwatch
          command: "echo $JAVA_HOME"
          register: "java_home"

        - name: "Debug java_home.stdout as part of a string"
          become: yes
          become_user: mwatch
          debug: msg={{ java_home.stdout_lines }}

        - name: "check hosts"
          become: yes
          become_user: mwatch
          command: "cat /etc/hosts"
          register: "etc_hosts"
